name: dlfcn-install

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-12
            python-version: "3.10"
      fail-fast: false
    steps:
    # - uses: actions/checkout@master
    #   with:
    #     name: dlfcn-win32/dlfcn-win32
    #     ref: refs/heads/release
    
    # - uses: actions/setup-python@v2
    #   with:
    #     python-version: ${{ matrix.python-version }}

    # - uses: awvwgk/setup-fortran@main
    #   id: setup-fortran
    #   with:
    #     compiler: gcc
    #     version: 11

    # - run: gcc -v -o hello.exe hello.c

    - run: |
        which gfortran
        curl -LJO https://github.com/fxcoudert/gfortran-for-macOS/releases/download/12.1-monterey/gfortran-Intel-12.1-Monterey.dmg
        hdiutil attach gfortran-Intel-12.1-Monterey.dmg
        sudo installer -package /Volumes/gfortran-Intel-12.1-Monterey/gfortran-Intel-12.1-Monterey/gfortran.pkg -target /
        sudo hdiutil detach /Volumes/gfortran-Intel-12.1-Monterey
    - run: |    
        which gfortran
        gfortran --version
        ls /usr/local/gfortran/bin
        export PATH=$PATH:/usr/local/gfortran/bin
        which gfortran  

    # - uses: actions/checkout@v3
    #   with:
    #     submodules: true

    # - uses: actions/setup-python@v2
    #   with:
    #     python-version: ${{ matrix.python-version }}
    # - uses: awvwgk/setup-fortran@main
    #   id: setup-fortran
    #   with:
    #     compiler: gcc
    #     version: 11
    # - run: python -m pip install --upgrade pip
    # - run: python -m pip install cmake
    # - run: curl -L