name: dlfcn-install

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            python-version: "3.10"
      fail-fast: false
    steps:
    # - uses: actions/checkout@master
    #   with:
    #     name: dlfcn-win32/dlfcn-win32
    #     ref: refs/heads/release
    
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: awvwgk/setup-fortran@main
      id: setup-fortran
      with:
        compiler: gcc
        version: 11

    - run: gcc -v -o hello.exe hello.c

    - run: |
        curl -LJO https://github.com/dlfcn-win32/dlfcn-win32/archive/refs/heads/master.zip
        unzip dlfcn-win32-master.zip
        python -m pip install --upgrade pip
        python -m pip install cmake
    - run: >    
        cmake -S ./dlfcn-win32-master -B ./build_dlfcn -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX="/c/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64"
    - run: |  
        cmake --build ./build_dlfcn
        cmake --install ./build_dlfcn   

    # - uses: actions/checkout@v3
    #   with:
    #     submodules: true

    # - uses: actions/setup-python@v2
    #   with:
    #     python-version: ${{ matrix.python-version }}
    # - uses: awvwgk/setup-fortran@main
    #   id: setup-fortran
    #   with:
    #     compiler: gcc
    #     version: 11
    # - run: python -m pip install --upgrade pip
    # - run: python -m pip install cmake
    # - run: curl -L

      
