name: github_condition_tests

on:
  workflow_dispatch:

  

  
  # push:
  #   tags:
  #    - 'v*'

jobs:
  Test_conditions:
    name: Print GITHUB CONTEXT
    runs-on: ubuntu-latest
    # if: ${{ github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v3
      - name: Show variables
        run: echo '${{ toJSON(github) }}'